---@class Palette
---@field bg string
---@field fg string
---@field selection string
---@field comment string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field purple string
---@field cyan string
---@field pink string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_magenta string
---@field bright_cyan string
---@field bright_white string
---@field menu string
---@field visual string
---@field gutter_fg string
---@field nontext string
---@field white string
---@field black string
return {
   fg = "#F8F8F2",
   bglighter = "#393649",
   bglight = "#2E2B3B",
   bg = "#22212C",
   bgdark = "#17161D",
   bgdarker = "#0B0B0F",
   comment = "#7970A9",
   selection = "#454158",
   subtle = "#424450",
   cyan = "#80FFEA",
   green = "#8AFF80",
   orange = "#FFCA80",
   pink = "#FF80BF",
   purple = "#9580FF",
   red = "#FF9580",
   yellow = "#FFFF80",
   bright_red = "#FF6E6E",
   bright_green = "#69FF94",
   bright_yellow = "#FFFFA5",
   bright_blue = "#D6ACFF",
   bright_magenta = "#FF92DF",
   bright_cyan = "#A4FFFF",
   bright_white = "#FFFFFF",
   menu = "#21222C",
   visual = "#3E4452",
   gutter_fg = "#4B5263",
   nontext = "#3B4048",
   white = "#ABB2BF",
   black = "#191A21",
}
